Question Five
write a python program to solve three linear equations using matrices. you can use the numpy library for matrix operations.

In [7]:
# Coefficients matrix
import numpy as np
coefficients = np.array([[4, 1, -2],
                        [-3, -1, 2],
                        [-1, 3, 2]])
print(coefficients)

[[ 4  1 -2]
 [-3 -1  2]
 [-1  3  2]]


In [8]:
# Constants column vector
import numpy as np
constants = np.array([6, -9, -1])
print(constants)


[ 6 -9 -1]


In [9]:
# Solve the system of equations
import numpy as np
solution = np.linalg.solve(coefficients, constants)
print(solution)

[-3.    3.5  -7.25]


In [10]:
# Print the solution
print("Solution:")
print("x =", solution[0])
print("y =", solution[1])
print("z =", solution[2])


Solution:
x = -3.0
y = 3.5
z = -7.25
