Question Four
construct a matrix below;[1, 0.2, 0.5
                          0.2, 1, 0.8
                          0.5, 0.8, 1] as a numpy array.
a. compute an inversion of t6he matrix(transpose)
b. Computer the (determinat) of the matrix if possible
c. Decompose the matrix.
d. Transform the matrix.

In [2]:
import numpy as np

# Create the matrix
matrix = np.array([[1, 0.2, 0.5],
                   [0.2, 1, 0.8],
                   [0.5, 0.8, 1]])

# Compute the inverse (transpose) of the matrix
inverse_matrix = np.linalg.inv(matrix)

print("Original Matrix:")
print(matrix)

print("\nInverse Matrix (Transpose):")
print(inverse_matrix)

Original Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]

Inverse Matrix (Transpose):
[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [3]:
# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print("\nDeterminant of the Matrix:", determinant)


Determinant of the Matrix: 0.2299999999999999


In [14]:
#matrix decomposition (LU decomposition)
lu_decomposition = np.linalg(matrix)
"myFunction"(lu_decomposition)
print("\nLU Decomposition:")
print("L matrix:")
print(lu_decomposition[1])
print("U matrix:")
print(lu_decomposition[2])

<>:3: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
<>:3: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?


TypeError: 'module' object is not callable

In [10]:
# Transform the matrix (scaling by a factor of 2)
scaled_matrix = matrix * 2

print("\nOriginal Matrix:")
print(matrix)
print("\nTransformed Matrix (Scaled by 2):")
print(scaled_matrix)


Original Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]

Transformed Matrix (Scaled by 2):
[[2.  0.4 1. ]
 [0.4 2.  1.6]
 [1.  1.6 2. ]]
